### ISSUE TITLE
Problema creazione query

### ISSUE THREAD

**Issue by capobecchino** [contactlab/contacthub-sdk-php#7]
Buongiorno, in questo file src\QueryBuilder\SimpleQuery.php c'è un piccolo problema:

alla riga 24:
```
public function build()
    {
        return [
            'type' => 'simple',
            'are' => $this->condition->build()
        ];
    }
```

dovrebbe invece diventare:

```
public function build()
{
    return [
        'type' => 'simple',
        'are' => [
            'condition' => $this->condition->build()
            ]
    ];
}
```

Grazie

**Comment by micheleorselli** [comment]
Ciao @capobecchino grazie per la segnalazione, procediamo a correggere

**Comment by edelprino** [comment]
Ciao @capobecchino ho appena pushato la nuova versione sistemata: https://github.com/contactlab/contacthub-sdk-php/tree/v1.0.1
