### ISSUE TITLE
Valore non corretto nel nome evento

### ISSUE THREAD

**Issue by DamienPirsy** [contactlab/contacthub-sdk-php#9]
Il valore corretto della costante   `const EVENT_NOT_SHOW`  è `'eventNoShow'`, non `'eventNotShow'` come indicato. Manca inoltre l'evento `eventRegistered`.

**Comment by micheleorselli** [comment]
graize per la segnalazione, fixiamo in breve!

**Comment by edelprino** [comment]
Ciao @DamienPirsy sistemato e pushato nella versione `v1.0.2`.
